proton: Don't exit on 64-bit steam.exe.so compilation failure. It will fail on Wine 7.21 with `/usr/bin/ld: /../lib64/wine/x86_64-unix/libwinecrt0.a(exe_entry.o): in function `__wine_spec_exe_entry': exe_entry.c:(.text+0x8d): undefined reference to `NtCurrentTeb'`. I have tested a few 64-bit games with success (they did load lsteamclient64 lib fine) so it seems to be a workable fallback for now.